# Generated by Django 5.2.3 on 2025-06-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="cover",
            field=models.ImageField(
                blank=True, null=True, upload_to="collections/covers/"
            ),
        ),
    ]
