# Generated by Django 5.2.3 on 2025-07-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_collection_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coin",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="coin",
            name="tirage",
            field=models.CharField(
                blank=True, default="Unknown", max_length=30, null=True
            ),
        ),
    ]
