# Generated by Django 5.2.3 on 2025-07-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0004_alter_coin_country_alter_coin_denomination_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="banknote",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coin",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="banknote",
            name="country",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="banknote",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="banknote",
            name="tirage",
            field=models.CharField(
                blank=True, default="Unknown", max_length=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="banknote",
            name="value",
            field=models.CharField(max_length=25),
        ),
    ]
