# Generated by Django 5.2.3 on 2025-07-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0005_banknote_description_coin_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="description",
            field=models.CharField(max_length=100),
        ),
    ]
