# Generated by Django 5.2.3 on 2025-07-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0006_alter_collection_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="name",
            field=models.CharField(max_length=60),
        ),
    ]
